### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by moriarty** [totalvoidness/jade-factory#1]
Hi,

Tomorrow is the final lecture, followed by the final lab class. So it is the final chance to show your project. 

I just wanted to check how development is going.
I know haven't been posting weekly reminders on LEA, but this is the only project where I haven't seen any commits since December... Perhaps you're already finished - I don't know. 

Tonight I sent out a reminder via LEA but I don't trust LEA to deliver the message in time. Hopefully you'll look here. 

Good Luck.

**Comment by overheadhunter** [comment]
Hey, we're up and running. We also got the Unity visualization working.

Cu tomorrow!

**Comment by moriarty** [comment]
Great! 

See you tomorrow.
